spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jackson:
    property-naming-strategy: SNAKE_CASE

  main:
    allow-bean-definition-overriding: true
jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_exp: ${JWT_ACCESS_EXP}
  refresh_exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

kakao:
  api-key: ${KAKAO_API_KEY}

socket:
  port: ${SOCKET_PORT}
