spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  redis:
    port: ${REDIS_PORT}
    host: ${REDIS_HOST}

  jackson:
    property-naming-strategy: SNAKE_CASE
    serialization:
      fail-on-empty-beans: false

  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 10MB
jwt:
  secret_key: ${JWT_SECRET_KEY}
  access_exp: ${JWT_ACCESS_EXP}
  refresh_exp: ${JWT_REFRESH_EXP}
  header: ${JWT_HEADER}
  prefix: ${JWT_PREFIX}

kakao:
  api-key: ${KAKAO_API_KEY}

cloud:
  aws:
    s3:
      prefix: ${AWS_S3_PREFIX}
      bucket: ${AWS_S3_BUCKET}
      base-image-url: ${AWS_S3_URL}
    region:
      static: ${AWS_S3_REGION}
    stack:
      auto: false
    credentials:
      access-key: ${AWS_S3_ACCESS}
      secret-key: ${AWS_S3_SECRET}

fcm:
  value: ${FCM_VALUE}
socket:
  port: ${SOCKET_PORT}
server:
  port: 8888
